/* volunteer type */
export const VOLUNTEER_GET_REQUEST = "VOLUNTEER_REGISTER_REQUEST";
export const VOLUNTEER_GET_SUCCESS = "VOLUNTEER_CREATE_SUCCESS";
export const VOLUNTEER_FAIL = "VOLUNTEER_FAIL";

/* become a volunteer */
export const BECOME_CREATE_REQUEST  = "BECOME_CREATE_REQUEST";
export const BECOME_CREATE_SUCCESS = "BECOME_CREATE_SUCCESS";
export const BECOME_FAIL = "BECOME_FAIL";

/* slider */
export const SLIDER_GET_REQUEST  = "SLIDER_GET_REQUEST";
export const SLIDER_GET_SUCCESS = "SLIDER_GET_SUCCESS";
export const SLIDER_GET_FAIL = "SLIDER_GET_FAIL";

/* slider */
export const CONTACT_CREATE_REQUEST  = "CONTACT_CREATE_REQUEST";
export const CONTACT_CREATE_SUCCESS = "CONTACT_CREATE_SUCCESS";
export const CONTACT_CREATE_FAIL = "CONTACT_CREATE_FAIL";